# Generated by Django 2.2.6 on 2019-10-24 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0003_auto_20191021_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='call_logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callTime', models.DateTimeField(auto_now_add=True, verbose_name='Çağrı Zamanı')),
                ('fromNumber', models.CharField(max_length=16, verbose_name='Arayan')),
                ('talkingDurations', models.DateTimeField(verbose_name='Görüşme Süresi')),
                ('note', models.TextField(verbose_name='Not')),
                ('id_contacts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rn_id_contacts', to='book.Contacts')),
                ('toUser', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rn_to_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-callTime'],
            },
        ),
    ]
