# Generated by Django 4.2.1 on 2023-06-02 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='call_logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callTime', models.DateTimeField(auto_now_add=True, verbose_name='Çağrı Zamanı')),
                ('fromNumber', models.CharField(max_length=16, verbose_name='Arayan')),
                ('note', models.TextField(verbose_name='Not')),
                ('id_contacts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rn_id_contacts', to='book.contacts', verbose_name='Kayıtlı Firma')),
                ('toUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rn_to_user', to=settings.AUTH_USER_MODEL, verbose_name='Cevaplayan Kullanıcı')),
            ],
            options={
                'ordering': ['-callTime'],
            },
        ),
    ]
