# Generated by Django 2.2.6 on 2019-10-24 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Call_Logs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call_logs',
            name='talkingDurations',
        ),
        migrations.AlterField(
            model_name='call_logs',
            name='id_contacts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rn_id_contacts', to='book.Contacts', verbose_name='Kayıtlı Firma'),
        ),
        migrations.AlterField(
            model_name='call_logs',
            name='toUser',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rn_to_user', to=settings.AUTH_USER_MODEL, verbose_name='Cevaplayan Kullanıcı'),
        ),
    ]
