# Generated by Django 2.2.6 on 2019-10-26 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Call_Logs', '0002_auto_20191024_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call_logs',
            name='toUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rn_to_user', to=settings.AUTH_USER_MODEL, verbose_name='Cevaplayan Kullanıcı'),
        ),
    ]
