# Generated by Django 4.2.1 on 2023-06-02 12:53

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('companyName', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('phoneNumber1', phone_field.models.PhoneField(max_length=31, unique=True)),
                ('phoneNumber2', phone_field.models.PhoneField(blank=True, max_length=31, null=True)),
                ('address', models.TextField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
