# Generated by Django 2.2.6 on 2019-10-21 11:36

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20191021_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='phoneNumber1',
            field=phone_field.models.PhoneField(max_length=31, unique=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phoneNumber2',
            field=phone_field.models.PhoneField(blank=True, max_length=31, unique=True),
        ),
    ]
