# Generated by Django 2.2.6 on 2019-10-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20191030_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='companyName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
