# Generated by Django 2.2.6 on 2019-11-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20191030_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='address',
            field=models.TextField(blank=True, max_length=254),
        ),
    ]
