# Generated by Django 2.2.6 on 2019-11-08 14:47

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20191108_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='companyName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phoneNumber2',
            field=phone_field.models.PhoneField(max_length=31, null=True, unique=True),
        ),
    ]
