# Generated by Django 2.2.6 on 2019-11-11 06:59

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20191108_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='address',
            field=models.TextField(blank=True, default=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='companyName',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.EmailField(blank=True, default=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phoneNumber2',
            field=phone_field.models.PhoneField(blank=True, default=True, max_length=31, unique=True),
        ),
    ]
