# Generated by Django 2.2.6 on 2019-11-11 08:24

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_auto_20191111_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='address',
            field=models.TextField(blank=True, default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phoneNumber2',
            field=phone_field.models.PhoneField(blank=True, default=None, max_length=31),
        ),
    ]
