# Generated by Django 2.2.6 on 2019-11-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_auto_20191112_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='companyName',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
    ]
